### ISSUE TITLE
BridgeID auslesen beim manuellen Hinzufügen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#11]
Wenn man eine Bridge manuell hinzufügt, muss die BridgeID anschließend ausgelesen werden, sonst kann bei einer falschen BridgeID die Callback-Funktion fehlschlagen. 

Aktuell wird die eingegebene BridgeID nicht überprüft. Zudem ist die in der app angezeigte BridgeID unterschiedlich zur BridgeID, die per JSON zurückkommt!

**Comment by christianTF** [comment]
Gefunden: Web BridgeID != Hardware BridgeID
https://developer.nuki.io/t/bridge-discovery-and-different-bridge-ids/2412/3?u=christiantf

Heißt, Add manually, Edit und Search braucht jeweils ein anschließendes /info, um die Hardware-ID zu setzen.

Die BridgeID brauchst du im „Add manually“ dann garnicht vom Benutzer abfragen.

**Comment by christianTF** [comment]
Nach ein paar Commits jetzt folgendes Verhalten:
Der Schlüssel für die Bridge im bridges.json:
- Bridge durch Discovery angelegt --> ServerID
- Bridge manuell angelegt --> "9" +  9-stellige Nummer. 
Diese ID ändert sich nie und ist immer der (interne) Key für die Bridge (intBridgeId).

JSON-Attribute pro Bridge:
- bridgeId:
  - Ist die Hardware ID der Bridge
  - Gibt es nur bei der Hardware-Bridge, nicht bei der Software-Bridge
  - Wird mit "" initialisiert beim Discovery
  - Wird mit "" initialisiert bei Add manually, wenn kein Token angegeben ist.
  - Wird bei Add und Edit mit der richtigen bridgeId befüllt, wenn der Token angegeben ist.
- discoveryBridgeId:
   - Ist die ID auf den Nuki-Servern (lt. Nuki: serverId)
   - Existiert nur, wenn das Cloud-Announce auf der Bridge aktiviert ist
   - Wird mit der serverId initialisiert beim Discovery
   - Wird mit "" initialisiert beim Add manually
   - Wird bei Add und Edit mit der richtigen serverId befüllt, wenn der Token angegeben ist und der Wert existiert.
- intBridgeId:
    - Ist identisch mit dem Json-Schlüssel. 
    - Wird beim Anlegen durch Discovery oder Add mit geschrieben
    - Muss exisiteren und ändert sich nie

``` json
{
   "948371003" : {
      "bridgeId" : 412345678,
      "discoveryBridgeId" : 598765432,
      "intBridgeId" : "948371003",
      "ip" : "192.168.0.21",
      "port" : "8080",
      "token" : "abcde"
   }
}
```
