### ISSUE TITLE
Im WebIf kein "undefined"

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#14]
Wenn ein Wert nicht definiert ist, soll das Feld im WebIf leer sein und nicht "undefined" angezeigt werden.

![image](https://user-images.githubusercontent.com/16830799/63565031-ad38e080-c567-11e9-8e1c-be57e32ead84.png)

**Comment by christianTF** [comment]
Token Undefined gefixt.
