### ISSUE TITLE
BridgeID nicht in Klammern

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#15]
Die BridgeID soll nicht in Klammern angezeigt werden.

Zudem: Welche BridgeID nehmen wir jetzt im WebIf? Hardware? Discovery? Eigene?

![image](https://user-images.githubusercontent.com/16830799/63565110-f2f5a900-c567-11e9-9755-6156dfd12156.png)

**Comment by christianTF** [comment]
In Klammern: intBridgeId
Ohne Klammern: bridgeId

Hab gelesen, nur Hardware-Bridge hat eine Hardware-ID, die Software-Bridge nicht.
Die discoveryBridgeId (Nuki selbst bezeichnet sie als ServerId) existiert nur, wenn Discovery auf der Bridge aktiviert ist.

Es gibt also by Nuki Design weder Hardware-Id noch Server-Id als festen Schlüssel. Vielleicht zeigen wir die Id einfach garnicht in der Übersicht an, sondern nur in den Details.

**Comment by mschlenstedt** [comment]
Passt so und ist logisch.
