### ISSUE TITLE
Hostnamen im Callback

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#16]
Das er beim Callback den Hostnamen nimmt zerschiesst zumindest bei mir die Konfiguration.

Ich hab den Hostnamen im LoxBerry WebIf nicht geändert (ist folglich per Default "loxberry"). In der Fritte habe ich aber dem LoxBerry den Namen "loxberrydevil" zugewiesen. 

Der Callback zeigt jetzt auf http://loxberry:80/plugins/nukismartlock/callback.php?lbuid=ouXDU und geht damit ins Leere...

Keine Ahnung, aber ich mach das mit der Fritte immer so... Vielleicht ist das ein genereller Bug im LoxBerry. Er müsste seinen Hostnamen eigentlich per DNS abfragen und dann selbst korrekt setzen. Oder per DHCP (kriegt er den mitgeliefert?) setzen. So ist es auf jeden Fall bei mir zerschossen.

**Comment by christianTF** [comment]
KISS: Wir nehmen fix die IP. Durch den Cronjob wird das jetzt eh, zumindest einmal pro Stunde, aktuell gehalten.

**Comment by mschlenstedt** [comment]
Und wir machen einen Hinweis im Wiki.
