### ISSUE TITLE
Nach Bridge hinzufügen Devices automatisch scannen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#17]
Wenn eine Bridge authentifiziert wird, soll automatisch nach neuen Devices gesucht werden.

**Comment by christianTF** [comment]
Siehe https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/issues/18#issuecomment-524235883

Evt. braucht es gar kein Speichern der Devices, sondern nur On-The-Fly.

**Comment by mschlenstedt** [comment]
Die devices.json brauchen wir nicht (mehr). Ich nehm' sie raus.

Edit: Wir lassen es vorerst so. Änderungen zu umfangreich,

**Comment by mschlenstedt** [comment]
devices.json nicht mehr löschen, sondern Variable leeren. Verhindert einen Schreibzugriff auf die SD.

**Comment by christianTF** [comment]
Umgesetzt ist:
- Bridge-Suche bzw. manuelles Anlegen einer Bridge führt *keine* Device-Suche aus.
- Aufruf des Formular _Devices_ führt *immer* eine Device-Suche aus.
- Das letzte Suchergebnis steht immer in der devices.json.
- Der Benutzer muss daher mindestens einmal _Devices_ geöffnet haben, damit die Cron-Routinen funktionieren.
