### ISSUE TITLE
Callbacks und Devices bereinigen nach Löschen von Bridges

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#18]
Wenn eine Bridge aus dem WebIf gelöscht wird, soll auch der Callback gelöscht werden. 

Zudem sollen auch alle zugehörigen Devices zur Bridge aus der Config entfernt werden (sollte gehen, indem "searchdevices" einfach erneut aufgerifen wird).

**Comment by christianTF** [comment]
Das Uninstall der Callbacks beim Löschen der Bridge ist drin.

Das andere lass ich dir.
Btw. braucht es eine devices.json? Nachdem es da nichts zu editieren gibt, reicht da eh der Abruf on-the-fly. Den Button könnte man trotzdem lassen, und "Retry Search" oder so ähnlich nennen.

**Comment by mschlenstedt** [comment]
Die devices.json brauchen wir nicht. Ist ein Überbleibsel, als noch nicht klar war, welche Funktionen benötigt werden.
