### ISSUE TITLE
Aktivierung (Auth) und Einrichten der Callbacks

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#2]
...fehlen noch

**Comment by mschlenstedt** [comment]
Auth ist implementiert. Registrierung des Callbacks über den Daemon.

**Comment by christianTF** [comment]
Callback-Handling ist jetzt auch in der index.cgi, und soll dann beim Einrichten übers UI, sowie stündlich per cron aufgerufen werden.

Das Problem ist derzeit, dass beim Call /callback/add die Bridge stirbt.
https://developer.nuki.io/t/random-http-503-unavailable/909/58?u=christiantf

**Comment by christianTF** [comment]
Perl: 
`($error, $message) = callback( $bridgeid );`

AJAX:
`ajax: 'callback', bridgeid: bridgeid`

Kannst du das bitte einbauen. 
Es sollte bei jedem Anlegen (Automatisch, Manuell) und jedem Editieren aufgerufen werden. Besser zu oft :-)

**Comment by christianTF** [comment]
Das Registrieren des Callbacks, das du bei Add/Edit eingebaut hast, scheint bei mir richtig zu funktionieren.
