### ISSUE TITLE
Template-Builder

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#5]
...muss noch integriert werden. Code vom MiRobot-Plugin: https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG

**Comment by mschlenstedt** [comment]
Soll gleich mit der neuen Template-Lib implementiert werden.

**Comment by christianTF** [comment]
Implemented with https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/commit/2997fadd6390a291f0091f3e747a00074f6c7971 and https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/commit/01a21dd12f10b6cd8b00407773cc569fecaf0aca
