### ISSUE TITLE
callback.php muss MQTT Konfiguration verwenden

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Nuki#6]
Aktuell noch Festwerte: https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/blob/master/webfrontend/html/callback.php

**Comment by christianTF** [comment]
Siehe Commit-Beschreibung von 69152152cb31424b410dc66bd97c6d5eba4ec3b3
