### ISSUE TITLE
Bridge Details Popup

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Nuki#7]
Ich habe hier https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/blob/f757eb206e2164dd0160e469e9f195e1c8be56ca/templates/settings.html#L139
bzw. hier https://github.com/mschlenstedt/LoxBerry-Plugin-Nuki/blob/f757eb206e2164dd0160e469e9f195e1c8be56ca/templates/settings.html#L486 einen Stub für eine Detailseite zur Bridge angelegt.

Geöffnet werden kann das Popup derzeit durch Klick auf die Bridge-ID, es steht aber noch nichts drin.

Hier können Details wie Firmware-Version usw. angezeigt werden, _wichtig_ wäre mir jedoch die Liste der Callbacks und eine Lösch-Funktion (Button) der Callbacks. 
Funktionen zum Listen und Löschen gibt es schon im index.cgi (aber noch ohne ajax=... Aufruf-Funktion), und der Response der Funktionen ist noch undefiniert.

Use-Case bei der Callback-Liste ist, dass man alte, falsche oder fremde Callbacks löschen kann. Ein Hinzufügen oder Editieren der Callbacks ist explizit nicht gewünscht.

**Comment by mschlenstedt** [comment]
Ich mach ein neues Issue zum Löschen der Callbacks auf.
